### PR TITLE
Implemented time-to-read in response

### PR DESCRIPTION
**Pull request by SunnyNagam**
Changed the response of /category to also return a variable called timeToRead representing the estimated time to read in minutes for each article

### CODE REVIEW

**Review by brian-norman — CHANGES_REQUESTED** [review]
Won't this be very inflated because of all the html tags in `text`? Also was this tested for (1) showing up in the main response and (2) if it actually reflects your reading time? If yes then I'm very excited for this yay :tada:

**Comment by SunnyNagam** [comment]
It was successfully tested for (1), but i'm not sure how to test it for (2) without reading a bunch of articles and timing myself lol, but the numbers seem reasonable

**Comment by brian-norman** [comment]
Yes read some articles. 😀

**Comment by brian-norman** [comment]
Jk lol

**Review by brian-norman — APPROVED** [review]

**Pull request merged**
